### ISSUE TITLE
Fix Navigation Bar

### ISSUE THREAD

**Issue by codestromer** [gcetOpenSourceSociety/Codechef-Local-chapter#15]
There are two navigation bars, Remove the old one.
Beautify navigation bar (move navigations to the right side of the bar)

**Comment by RyanWils** [comment]
Hi I would like to do this issue. 
I created a mock up, if you like it I will create a PR for it.

![image](https://user-images.githubusercontent.com/49354833/66531471-e0b0d980-ead9-11e9-92fd-fb2558d49b0c.png)

**Comment by bharat1510** [comment]
PR#16
