### ISSUE TITLE
Add comments to index.html

### ISSUE THREAD

**Issue by cTxplorer** [gcetOpenSourceSociety/Codechef-Local-chapter#6]
Add proper comments for each section of code mentioning what it is doing.

**Comment by jpacsai** [comment]
Hi I would like to work on this issue :)

**Comment by cTxplorer** [comment]
@jpacsai assigning this to you :) 
plz try to create PR in 24 hrs..

**Comment by cTxplorer** [comment]
#8 Solves this issue
